name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # This line is the fix! It links the SDK to the builder
          sdk: nightly
          combine: true
        env:
          # Adding this environment variable helps CMake find the SDK
          GEODE_SDK: ${{ github.workspace }}/geode-sdk
